// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetTasksByTaskIdData, GetTasksByTaskIdErrors, GetTasksByTaskIdResponses, GetTasksData, GetTasksErrors, GetTasksResponses, PostTasksData, PostTasksErrors, PostTasksResponses, PutTasksByTaskIdNameData, PutTasksByTaskIdNameErrors, PutTasksByTaskIdNameResponses, PutTasksByTaskIdStatusCancelData, PutTasksByTaskIdStatusCancelErrors, PutTasksByTaskIdStatusCancelResponses, PutTasksByTaskIdStatusDoneData, PutTasksByTaskIdStatusDoneErrors, PutTasksByTaskIdStatusDoneResponses, PutTasksByTaskIdStatusPendingData, PutTasksByTaskIdStatusPendingErrors, PutTasksByTaskIdStatusPendingResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Lists tasks
 */
export const getTasks = <ThrowOnError extends boolean = false>(options?: Options<GetTasksData, ThrowOnError>) => (options?.client ?? client).get<GetTasksResponses, GetTasksErrors, ThrowOnError>({
    responseType: 'json',
    url: '/tasks',
    ...options
});

/**
 * Adds a new task.
 */
export const postTasks = <ThrowOnError extends boolean = false>(options: Options<PostTasksData, ThrowOnError>) => (options.client ?? client).post<PostTasksResponses, PostTasksErrors, ThrowOnError>({
    responseType: 'json',
    url: '/tasks',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Gets a single task.
 */
export const getTasksByTaskId = <ThrowOnError extends boolean = false>(options: Options<GetTasksByTaskIdData, ThrowOnError>) => (options.client ?? client).get<GetTasksByTaskIdResponses, GetTasksByTaskIdErrors, ThrowOnError>({
    responseType: 'json',
    url: '/tasks/{task_id}',
    ...options
});

/**
 * Renames a task.
 */
export const putTasksByTaskIdName = <ThrowOnError extends boolean = false>(options: Options<PutTasksByTaskIdNameData, ThrowOnError>) => (options.client ?? client).put<PutTasksByTaskIdNameResponses, PutTasksByTaskIdNameErrors, ThrowOnError>({
    responseType: 'json',
    url: '/tasks/{task_id}/name',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Mark the task as cancelled.
 */
export const putTasksByTaskIdStatusCancel = <ThrowOnError extends boolean = false>(options: Options<PutTasksByTaskIdStatusCancelData, ThrowOnError>) => (options.client ?? client).put<PutTasksByTaskIdStatusCancelResponses, PutTasksByTaskIdStatusCancelErrors, ThrowOnError>({
    responseType: 'json',
    url: '/tasks/{task_id}/status/cancel',
    ...options
});

/**
 * Mark the task as done.
 */
export const putTasksByTaskIdStatusDone = <ThrowOnError extends boolean = false>(options: Options<PutTasksByTaskIdStatusDoneData, ThrowOnError>) => (options.client ?? client).put<PutTasksByTaskIdStatusDoneResponses, PutTasksByTaskIdStatusDoneErrors, ThrowOnError>({
    responseType: 'json',
    url: '/tasks/{task_id}/status/done',
    ...options
});

/**
 * Mark the task as pending.
 */
export const putTasksByTaskIdStatusPending = <ThrowOnError extends boolean = false>(options: Options<PutTasksByTaskIdStatusPendingData, ThrowOnError>) => (options.client ?? client).put<PutTasksByTaskIdStatusPendingResponses, PutTasksByTaskIdStatusPendingErrors, ThrowOnError>({
    responseType: 'json',
    url: '/tasks/{task_id}/status/pending',
    ...options
});
