// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AddTaskData, AddTaskErrors, AddTaskResponses, GetTaskData, GetTaskErrors, GetTaskResponses, ListTasksData, ListTasksErrors, ListTasksResponses, RenameTaskData, RenameTaskErrors, RenameTaskResponses, SetCancelledData, SetCancelledErrors, SetCancelledResponses, SetDoneData, SetDoneErrors, SetDoneResponses, SetPendingData, SetPendingErrors, SetPendingResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Lists tasks
 */
export const listTasks = <ThrowOnError extends boolean = false>(options?: Options<ListTasksData, ThrowOnError>) => (options?.client ?? client).get<ListTasksResponses, ListTasksErrors, ThrowOnError>({
    responseType: 'json',
    url: '/tasks',
    ...options
});

/**
 * Adds a new task.
 */
export const addTask = <ThrowOnError extends boolean = false>(options: Options<AddTaskData, ThrowOnError>) => (options.client ?? client).post<AddTaskResponses, AddTaskErrors, ThrowOnError>({
    responseType: 'json',
    url: '/tasks',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Gets a single task.
 */
export const getTask = <ThrowOnError extends boolean = false>(options: Options<GetTaskData, ThrowOnError>) => (options.client ?? client).get<GetTaskResponses, GetTaskErrors, ThrowOnError>({
    responseType: 'json',
    url: '/tasks/{task_id}',
    ...options
});

/**
 * Renames a task.
 */
export const renameTask = <ThrowOnError extends boolean = false>(options: Options<RenameTaskData, ThrowOnError>) => (options.client ?? client).put<RenameTaskResponses, RenameTaskErrors, ThrowOnError>({
    responseType: 'json',
    url: '/tasks/{task_id}/name',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Mark the task as cancelled.
 */
export const setCancelled = <ThrowOnError extends boolean = false>(options: Options<SetCancelledData, ThrowOnError>) => (options.client ?? client).put<SetCancelledResponses, SetCancelledErrors, ThrowOnError>({
    responseType: 'json',
    url: '/tasks/{task_id}/status/cancel',
    ...options
});

/**
 * Mark the task as done.
 */
export const setDone = <ThrowOnError extends boolean = false>(options: Options<SetDoneData, ThrowOnError>) => (options.client ?? client).put<SetDoneResponses, SetDoneErrors, ThrowOnError>({
    responseType: 'json',
    url: '/tasks/{task_id}/status/done',
    ...options
});

/**
 * Mark the task as pending.
 */
export const setPending = <ThrowOnError extends boolean = false>(options: Options<SetPendingData, ThrowOnError>) => (options.client ?? client).put<SetPendingResponses, SetPendingErrors, ThrowOnError>({
    responseType: 'json',
    url: '/tasks/{task_id}/status/pending',
    ...options
});
