/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * TODO example (Groom)
 * Shows how to structure backend with three-layer architecture and generate spec for frontend.
 * OpenAPI spec version: 0.0.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/vue-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType
} from '@tanstack/vue-query';

import {
  computed,
  unref
} from 'vue';
import type {
  MaybeRef
} from 'vue';

/**
 * Request body
 */
export interface AddTaskRequest {
  title: string;
}

export type OrderDirection = typeof OrderDirection[keyof typeof OrderDirection];


export const OrderDirection = {
  Asc: 'Asc',
  Desc: 'Desc',
} as const;

/**
 * Request body
 */
export interface RenameTaskRequest {
  title: string;
}

export type Status = typeof Status[keyof typeof Status];


export const Status = {
  Pending: 'Pending',
  Done: 'Done',
  Cancelled: 'Cancelled',
} as const;

export type TaskOrderBy = typeof TaskOrderBy[keyof typeof TaskOrderBy];


export const TaskOrderBy = {
  Id: 'Id',
  Title: 'Title',
  Status: 'Status',
} as const;

export interface TaskViewModel {
  /** @minimum 0 */
  id: number;
  status: Status;
  title: string;
}

export type VecItem = {
  /** @minimum 0 */
  id: number;
  status: Status;
  title: string;
};

export type Vec = VecItem[];

export type GetTaskParams = {
/**
 * @nullable
 */
title?: string | null;
/**
 * @nullable
 */
status?: Status[] | null;
sort_by?: TaskOrderBy;
order?: OrderDirection;
};

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




export type getTaskResponse200 = {
  data: Vec
  status: 200
}

export type getTaskResponse500 = {
  data: void
  status: 500
}

export type getTaskResponseSuccess = (getTaskResponse200) & {
  headers: Headers;
};
export type getTaskResponseError = (getTaskResponse500) & {
  headers: Headers;
};

export type getTaskResponse = (getTaskResponseSuccess | getTaskResponseError)

export const getGetTaskUrl = (params?: GetTaskParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/task?${stringifiedParams}` : `/task`
}

/**
 * @summary Lists tasks
 */
export const getTask = async (params?: GetTaskParams, options?: RequestInit): Promise<getTaskResponse> => {

  const res = await fetch(getGetTaskUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getTaskResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getTaskResponse
}





export const getGetTaskQueryKey = (params?: MaybeRef<GetTaskParams>,) => {
    return [
    'task', ...(params ? [params] : [])
    ] as const;
    }


export const getGetTaskQueryOptions = <TData = Awaited<ReturnType<typeof getTask>>, TError = void>(params?: MaybeRef<GetTaskParams>, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getTask>>, TError, TData>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  getGetTaskQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTask>>> = ({ signal }) => getTask(unref(params), { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTask>>, TError, TData>
}

export type GetTaskQueryResult = NonNullable<Awaited<ReturnType<typeof getTask>>>
export type GetTaskQueryError = void


/**
 * @summary Lists tasks
 */

export function useGetTask<TData = Awaited<ReturnType<typeof getTask>>, TError = void>(
 params?: MaybeRef<GetTaskParams>, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getTask>>, TError, TData>, fetch?: RequestInit}

 ): UseQueryReturnType<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetTaskQueryOptions(params,options)

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & { queryKey: QueryKey };

  query.queryKey = unref(queryOptions).queryKey as QueryKey;

  return query;
}







export type postTaskResponse200 = {
  data: TaskViewModel
  status: 200
}

export type postTaskResponse400 = {
  data: string
  status: 400
}

export type postTaskResponse409 = {
  data: void
  status: 409
}

export type postTaskResponse500 = {
  data: void
  status: 500
}

export type postTaskResponseSuccess = (postTaskResponse200) & {
  headers: Headers;
};
export type postTaskResponseError = (postTaskResponse400 | postTaskResponse409 | postTaskResponse500) & {
  headers: Headers;
};

export type postTaskResponse = (postTaskResponseSuccess | postTaskResponseError)

export const getPostTaskUrl = () => {




  return `/task`
}

/**
 * @summary Adds a new task.
 */
export const postTask = async (addTaskRequest: AddTaskRequest, options?: RequestInit): Promise<postTaskResponse> => {

  const res = await fetch(getPostTaskUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(addTaskRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postTaskResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postTaskResponse
}




export const getPostTaskMutationOptions = <TError = string | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postTask>>, TError,{data: AddTaskRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postTask>>, TError,{data: AddTaskRequest}, TContext> => {

const mutationKey = ['postTask'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postTask>>, {data: AddTaskRequest}> = (props) => {
          const {data} = props ?? {};

          return  postTask(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostTaskMutationResult = NonNullable<Awaited<ReturnType<typeof postTask>>>
    export type PostTaskMutationBody = AddTaskRequest
    export type PostTaskMutationError = string | void

    /**
 * @summary Adds a new task.
 */
export const usePostTask = <TError = string | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postTask>>, TError,{data: AddTaskRequest}, TContext>, fetch?: RequestInit}
 ): UseMutationReturnType<
        Awaited<ReturnType<typeof postTask>>,
        TError,
        {data: AddTaskRequest},
        TContext
      > => {
      return useMutation(getPostTaskMutationOptions(options));
    }

export type getTaskTaskIdResponse200 = {
  data: TaskViewModel
  status: 200
}

export type getTaskTaskIdResponse404 = {
  data: void
  status: 404
}

export type getTaskTaskIdResponse500 = {
  data: void
  status: 500
}

export type getTaskTaskIdResponseSuccess = (getTaskTaskIdResponse200) & {
  headers: Headers;
};
export type getTaskTaskIdResponseError = (getTaskTaskIdResponse404 | getTaskTaskIdResponse500) & {
  headers: Headers;
};

export type getTaskTaskIdResponse = (getTaskTaskIdResponseSuccess | getTaskTaskIdResponseError)

export const getGetTaskTaskIdUrl = (taskId: number,) => {




  return `/task/${taskId}`
}

/**
 * @summary Gets a single task.
 */
export const getTaskTaskId = async (taskId: number, options?: RequestInit): Promise<getTaskTaskIdResponse> => {

  const res = await fetch(getGetTaskTaskIdUrl(taskId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getTaskTaskIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getTaskTaskIdResponse
}





export const getGetTaskTaskIdQueryKey = (taskId: MaybeRef<number>,) => {
    return [
    'task',taskId
    ] as const;
    }


export const getGetTaskTaskIdQueryOptions = <TData = Awaited<ReturnType<typeof getTaskTaskId>>, TError = void>(taskId: MaybeRef<number>, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getTaskTaskId>>, TError, TData>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  getGetTaskTaskIdQueryKey(taskId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTaskTaskId>>> = ({ signal }) => getTaskTaskId(unref(taskId), { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: computed(() => unref(taskId) !== null && unref(taskId) !== undefined), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTaskTaskId>>, TError, TData>
}

export type GetTaskTaskIdQueryResult = NonNullable<Awaited<ReturnType<typeof getTaskTaskId>>>
export type GetTaskTaskIdQueryError = void


/**
 * @summary Gets a single task.
 */

export function useGetTaskTaskId<TData = Awaited<ReturnType<typeof getTaskTaskId>>, TError = void>(
 taskId: MaybeRef<number>, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getTaskTaskId>>, TError, TData>, fetch?: RequestInit}

 ): UseQueryReturnType<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetTaskTaskIdQueryOptions(taskId,options)

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & { queryKey: QueryKey };

  query.queryKey = unref(queryOptions).queryKey as QueryKey;

  return query;
}







export type putTaskTaskIdNameResponse200 = {
  data: TaskViewModel
  status: 200
}

export type putTaskTaskIdNameResponse400 = {
  data: string
  status: 400
}

export type putTaskTaskIdNameResponse404 = {
  data: void
  status: 404
}

export type putTaskTaskIdNameResponse409 = {
  data: void
  status: 409
}

export type putTaskTaskIdNameResponse500 = {
  data: void
  status: 500
}

export type putTaskTaskIdNameResponseSuccess = (putTaskTaskIdNameResponse200) & {
  headers: Headers;
};
export type putTaskTaskIdNameResponseError = (putTaskTaskIdNameResponse400 | putTaskTaskIdNameResponse404 | putTaskTaskIdNameResponse409 | putTaskTaskIdNameResponse500) & {
  headers: Headers;
};

export type putTaskTaskIdNameResponse = (putTaskTaskIdNameResponseSuccess | putTaskTaskIdNameResponseError)

export const getPutTaskTaskIdNameUrl = (taskId: number,) => {




  return `/task/${taskId}/name`
}

/**
 * @summary Renames a task.
 */
export const putTaskTaskIdName = async (taskId: number,
    renameTaskRequest: RenameTaskRequest, options?: RequestInit): Promise<putTaskTaskIdNameResponse> => {

  const res = await fetch(getPutTaskTaskIdNameUrl(taskId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(renameTaskRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: putTaskTaskIdNameResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as putTaskTaskIdNameResponse
}




export const getPutTaskTaskIdNameMutationOptions = <TError = string | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putTaskTaskIdName>>, TError,{taskId: number;data: RenameTaskRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof putTaskTaskIdName>>, TError,{taskId: number;data: RenameTaskRequest}, TContext> => {

const mutationKey = ['putTaskTaskIdName'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putTaskTaskIdName>>, {taskId: number;data: RenameTaskRequest}> = (props) => {
          const {taskId,data} = props ?? {};

          return  putTaskTaskIdName(taskId,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutTaskTaskIdNameMutationResult = NonNullable<Awaited<ReturnType<typeof putTaskTaskIdName>>>
    export type PutTaskTaskIdNameMutationBody = RenameTaskRequest
    export type PutTaskTaskIdNameMutationError = string | void

    /**
 * @summary Renames a task.
 */
export const usePutTaskTaskIdName = <TError = string | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putTaskTaskIdName>>, TError,{taskId: number;data: RenameTaskRequest}, TContext>, fetch?: RequestInit}
 ): UseMutationReturnType<
        Awaited<ReturnType<typeof putTaskTaskIdName>>,
        TError,
        {taskId: number;data: RenameTaskRequest},
        TContext
      > => {
      return useMutation(getPutTaskTaskIdNameMutationOptions(options));
    }

export type putTaskTaskIdStatusCancelResponse200 = {
  data: TaskViewModel
  status: 200
}

export type putTaskTaskIdStatusCancelResponse404 = {
  data: void
  status: 404
}

export type putTaskTaskIdStatusCancelResponse409 = {
  data: void
  status: 409
}

export type putTaskTaskIdStatusCancelResponse500 = {
  data: void
  status: 500
}

export type putTaskTaskIdStatusCancelResponseSuccess = (putTaskTaskIdStatusCancelResponse200) & {
  headers: Headers;
};
export type putTaskTaskIdStatusCancelResponseError = (putTaskTaskIdStatusCancelResponse404 | putTaskTaskIdStatusCancelResponse409 | putTaskTaskIdStatusCancelResponse500) & {
  headers: Headers;
};

export type putTaskTaskIdStatusCancelResponse = (putTaskTaskIdStatusCancelResponseSuccess | putTaskTaskIdStatusCancelResponseError)

export const getPutTaskTaskIdStatusCancelUrl = (taskId: number,) => {




  return `/task/${taskId}/status/cancel`
}

/**
 * @summary Mark the task as cancelled.
 */
export const putTaskTaskIdStatusCancel = async (taskId: number, options?: RequestInit): Promise<putTaskTaskIdStatusCancelResponse> => {

  const res = await fetch(getPutTaskTaskIdStatusCancelUrl(taskId),
  {
    ...options,
    method: 'PUT'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: putTaskTaskIdStatusCancelResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as putTaskTaskIdStatusCancelResponse
}




export const getPutTaskTaskIdStatusCancelMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putTaskTaskIdStatusCancel>>, TError,{taskId: number}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof putTaskTaskIdStatusCancel>>, TError,{taskId: number}, TContext> => {

const mutationKey = ['putTaskTaskIdStatusCancel'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putTaskTaskIdStatusCancel>>, {taskId: number}> = (props) => {
          const {taskId} = props ?? {};

          return  putTaskTaskIdStatusCancel(taskId,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutTaskTaskIdStatusCancelMutationResult = NonNullable<Awaited<ReturnType<typeof putTaskTaskIdStatusCancel>>>

    export type PutTaskTaskIdStatusCancelMutationError = void

    /**
 * @summary Mark the task as cancelled.
 */
export const usePutTaskTaskIdStatusCancel = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putTaskTaskIdStatusCancel>>, TError,{taskId: number}, TContext>, fetch?: RequestInit}
 ): UseMutationReturnType<
        Awaited<ReturnType<typeof putTaskTaskIdStatusCancel>>,
        TError,
        {taskId: number},
        TContext
      > => {
      return useMutation(getPutTaskTaskIdStatusCancelMutationOptions(options));
    }

export type putTaskTaskIdStatusDoneResponse200 = {
  data: TaskViewModel
  status: 200
}

export type putTaskTaskIdStatusDoneResponse404 = {
  data: void
  status: 404
}

export type putTaskTaskIdStatusDoneResponse409 = {
  data: void
  status: 409
}

export type putTaskTaskIdStatusDoneResponse500 = {
  data: void
  status: 500
}

export type putTaskTaskIdStatusDoneResponseSuccess = (putTaskTaskIdStatusDoneResponse200) & {
  headers: Headers;
};
export type putTaskTaskIdStatusDoneResponseError = (putTaskTaskIdStatusDoneResponse404 | putTaskTaskIdStatusDoneResponse409 | putTaskTaskIdStatusDoneResponse500) & {
  headers: Headers;
};

export type putTaskTaskIdStatusDoneResponse = (putTaskTaskIdStatusDoneResponseSuccess | putTaskTaskIdStatusDoneResponseError)

export const getPutTaskTaskIdStatusDoneUrl = (taskId: number,) => {




  return `/task/${taskId}/status/done`
}

/**
 * @summary Mark the task as done.
 */
export const putTaskTaskIdStatusDone = async (taskId: number, options?: RequestInit): Promise<putTaskTaskIdStatusDoneResponse> => {

  const res = await fetch(getPutTaskTaskIdStatusDoneUrl(taskId),
  {
    ...options,
    method: 'PUT'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: putTaskTaskIdStatusDoneResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as putTaskTaskIdStatusDoneResponse
}




export const getPutTaskTaskIdStatusDoneMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putTaskTaskIdStatusDone>>, TError,{taskId: number}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof putTaskTaskIdStatusDone>>, TError,{taskId: number}, TContext> => {

const mutationKey = ['putTaskTaskIdStatusDone'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putTaskTaskIdStatusDone>>, {taskId: number}> = (props) => {
          const {taskId} = props ?? {};

          return  putTaskTaskIdStatusDone(taskId,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutTaskTaskIdStatusDoneMutationResult = NonNullable<Awaited<ReturnType<typeof putTaskTaskIdStatusDone>>>

    export type PutTaskTaskIdStatusDoneMutationError = void

    /**
 * @summary Mark the task as done.
 */
export const usePutTaskTaskIdStatusDone = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putTaskTaskIdStatusDone>>, TError,{taskId: number}, TContext>, fetch?: RequestInit}
 ): UseMutationReturnType<
        Awaited<ReturnType<typeof putTaskTaskIdStatusDone>>,
        TError,
        {taskId: number},
        TContext
      > => {
      return useMutation(getPutTaskTaskIdStatusDoneMutationOptions(options));
    }

export type putTaskTaskIdStatusPendingResponse200 = {
  data: TaskViewModel
  status: 200
}

export type putTaskTaskIdStatusPendingResponse404 = {
  data: void
  status: 404
}

export type putTaskTaskIdStatusPendingResponse409 = {
  data: void
  status: 409
}

export type putTaskTaskIdStatusPendingResponse500 = {
  data: void
  status: 500
}

export type putTaskTaskIdStatusPendingResponseSuccess = (putTaskTaskIdStatusPendingResponse200) & {
  headers: Headers;
};
export type putTaskTaskIdStatusPendingResponseError = (putTaskTaskIdStatusPendingResponse404 | putTaskTaskIdStatusPendingResponse409 | putTaskTaskIdStatusPendingResponse500) & {
  headers: Headers;
};

export type putTaskTaskIdStatusPendingResponse = (putTaskTaskIdStatusPendingResponseSuccess | putTaskTaskIdStatusPendingResponseError)

export const getPutTaskTaskIdStatusPendingUrl = (taskId: number,) => {




  return `/task/${taskId}/status/pending`
}

/**
 * @summary Mark the task as pending.
 */
export const putTaskTaskIdStatusPending = async (taskId: number, options?: RequestInit): Promise<putTaskTaskIdStatusPendingResponse> => {

  const res = await fetch(getPutTaskTaskIdStatusPendingUrl(taskId),
  {
    ...options,
    method: 'PUT'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: putTaskTaskIdStatusPendingResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as putTaskTaskIdStatusPendingResponse
}




export const getPutTaskTaskIdStatusPendingMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putTaskTaskIdStatusPending>>, TError,{taskId: number}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof putTaskTaskIdStatusPending>>, TError,{taskId: number}, TContext> => {

const mutationKey = ['putTaskTaskIdStatusPending'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putTaskTaskIdStatusPending>>, {taskId: number}> = (props) => {
          const {taskId} = props ?? {};

          return  putTaskTaskIdStatusPending(taskId,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutTaskTaskIdStatusPendingMutationResult = NonNullable<Awaited<ReturnType<typeof putTaskTaskIdStatusPending>>>

    export type PutTaskTaskIdStatusPendingMutationError = void

    /**
 * @summary Mark the task as pending.
 */
export const usePutTaskTaskIdStatusPending = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putTaskTaskIdStatusPending>>, TError,{taskId: number}, TContext>, fetch?: RequestInit}
 ): UseMutationReturnType<
        Awaited<ReturnType<typeof putTaskTaskIdStatusPending>>,
        TError,
        {taskId: number},
        TContext
      > => {
      return useMutation(getPutTaskTaskIdStatusPendingMutationOptions(options));
    }
