// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * Request body
 */
export type AddTaskRequest = {
    title: string;
};

export type OrderDirection = 'Asc' | 'Desc';

/**
 * Request body
 */
export type RenameTaskRequest = {
    title: string;
};

export type Status = 'Pending' | 'Done' | 'Cancelled';

export type TaskList = Array<TaskViewModel>;

export type TaskOrderBy = 'Id' | 'Title' | 'Status';

export type TaskViewModel = {
    id: number;
    status: Status;
    title: string;
};

export type GetTasksData = {
    body?: never;
    path?: never;
    query?: {
        title?: string | null;
        status?: Array<Status> | null;
        sort_by?: TaskOrderBy;
        order?: OrderDirection;
    };
    url: '/tasks';
};

export type GetTasksErrors = {
    500: unknown;
};

export type GetTasksResponses = {
    200: TaskList;
};

export type GetTasksResponse = GetTasksResponses[keyof GetTasksResponses];

export type PostTasksData = {
    /**
     * Request body
     */
    body: AddTaskRequest;
    path?: never;
    query?: never;
    url: '/tasks';
};

export type PostTasksErrors = {
    /**
     * Malformed request, e.g. missing title or title is too long.
     */
    400: string;
    /**
     * Task already exists with the same title
     */
    409: unknown;
    /**
     * Unexpected error when adding a task, e.g. database is down or serialization error.
     */
    500: unknown;
};

export type PostTasksError = PostTasksErrors[keyof PostTasksErrors];

export type PostTasksResponses = {
    /**
     * Task added successfully
     */
    200: TaskViewModel;
};

export type PostTasksResponse = PostTasksResponses[keyof PostTasksResponses];

export type GetTasksByTaskIdData = {
    body?: never;
    path: {
        task_id: number;
    };
    query?: never;
    url: '/tasks/{task_id}';
};

export type GetTasksByTaskIdErrors = {
    404: unknown;
    500: unknown;
};

export type GetTasksByTaskIdResponses = {
    200: TaskViewModel;
};

export type GetTasksByTaskIdResponse = GetTasksByTaskIdResponses[keyof GetTasksByTaskIdResponses];

export type PutTasksByTaskIdNameData = {
    /**
     * Request body
     */
    body: RenameTaskRequest;
    path: {
        task_id: number;
    };
    query?: never;
    url: '/tasks/{task_id}/name';
};

export type PutTasksByTaskIdNameErrors = {
    400: string;
    404: unknown;
    409: unknown;
    500: unknown;
};

export type PutTasksByTaskIdNameError = PutTasksByTaskIdNameErrors[keyof PutTasksByTaskIdNameErrors];

export type PutTasksByTaskIdNameResponses = {
    200: TaskViewModel;
};

export type PutTasksByTaskIdNameResponse = PutTasksByTaskIdNameResponses[keyof PutTasksByTaskIdNameResponses];

export type PutTasksByTaskIdStatusCancelData = {
    body?: never;
    path: {
        task_id: number;
    };
    query?: never;
    url: '/tasks/{task_id}/status/cancel';
};

export type PutTasksByTaskIdStatusCancelErrors = {
    404: unknown;
    409: unknown;
    500: unknown;
};

export type PutTasksByTaskIdStatusCancelResponses = {
    200: TaskViewModel;
};

export type PutTasksByTaskIdStatusCancelResponse = PutTasksByTaskIdStatusCancelResponses[keyof PutTasksByTaskIdStatusCancelResponses];

export type PutTasksByTaskIdStatusDoneData = {
    body?: never;
    path: {
        task_id: number;
    };
    query?: never;
    url: '/tasks/{task_id}/status/done';
};

export type PutTasksByTaskIdStatusDoneErrors = {
    404: unknown;
    409: unknown;
    500: unknown;
};

export type PutTasksByTaskIdStatusDoneResponses = {
    200: TaskViewModel;
};

export type PutTasksByTaskIdStatusDoneResponse = PutTasksByTaskIdStatusDoneResponses[keyof PutTasksByTaskIdStatusDoneResponses];

export type PutTasksByTaskIdStatusPendingData = {
    body?: never;
    path: {
        task_id: number;
    };
    query?: never;
    url: '/tasks/{task_id}/status/pending';
};

export type PutTasksByTaskIdStatusPendingErrors = {
    404: unknown;
    409: unknown;
    500: unknown;
};

export type PutTasksByTaskIdStatusPendingResponses = {
    200: TaskViewModel;
};

export type PutTasksByTaskIdStatusPendingResponse = PutTasksByTaskIdStatusPendingResponses[keyof PutTasksByTaskIdStatusPendingResponses];
