// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * Request body
 */
export type AddTaskRequest = {
    title: string;
};

/**
 * Request body
 */
export type RenameTaskRequest = {
    title: string;
};

export type SortDirection = 'asc' | 'desc';

export type Status = 'Pending' | 'Done' | 'Cancelled';

export type TaskList = Array<TaskViewModel>;

export type TaskViewModel = {
    id: number;
    status: Status;
    title: string;
};

export type TasksSortBy = 'id' | 'title' | 'status';

export type ListTasksData = {
    body?: never;
    path?: never;
    query?: {
        title?: string | null;
        status?: Array<Status> | null;
        sort_by?: TasksSortBy;
        order?: SortDirection;
    };
    url: '/tasks';
};

export type ListTasksErrors = {
    500: unknown;
};

export type ListTasksResponses = {
    200: TaskList;
};

export type ListTasksResponse = ListTasksResponses[keyof ListTasksResponses];

export type AddTaskData = {
    /**
     * Request body
     */
    body: AddTaskRequest;
    path?: never;
    query?: never;
    url: '/tasks';
};

export type AddTaskErrors = {
    /**
     * Malformed request, e.g. missing title or title is too long.
     */
    400: string;
    /**
     * Task already exists with the same title
     */
    409: unknown;
    /**
     * Unexpected error when adding a task, e.g. database is down or serialization error.
     */
    500: unknown;
};

export type AddTaskError = AddTaskErrors[keyof AddTaskErrors];

export type AddTaskResponses = {
    /**
     * Task added successfully
     */
    200: TaskViewModel;
};

export type AddTaskResponse = AddTaskResponses[keyof AddTaskResponses];

export type GetTaskData = {
    body?: never;
    path: {
        task_id: number;
    };
    query?: never;
    url: '/tasks/{task_id}';
};

export type GetTaskErrors = {
    404: unknown;
    500: unknown;
};

export type GetTaskResponses = {
    200: TaskViewModel;
};

export type GetTaskResponse = GetTaskResponses[keyof GetTaskResponses];

export type RenameTaskData = {
    /**
     * Request body
     */
    body: RenameTaskRequest;
    path: {
        task_id: number;
    };
    query?: never;
    url: '/tasks/{task_id}/name';
};

export type RenameTaskErrors = {
    400: string;
    404: unknown;
    409: unknown;
    500: unknown;
};

export type RenameTaskError = RenameTaskErrors[keyof RenameTaskErrors];

export type RenameTaskResponses = {
    200: TaskViewModel;
};

export type RenameTaskResponse = RenameTaskResponses[keyof RenameTaskResponses];

export type SetCancelledData = {
    body?: never;
    path: {
        task_id: number;
    };
    query?: never;
    url: '/tasks/{task_id}/status/cancel';
};

export type SetCancelledErrors = {
    404: unknown;
    409: unknown;
    500: unknown;
};

export type SetCancelledResponses = {
    200: TaskViewModel;
};

export type SetCancelledResponse = SetCancelledResponses[keyof SetCancelledResponses];

export type SetDoneData = {
    body?: never;
    path: {
        task_id: number;
    };
    query?: never;
    url: '/tasks/{task_id}/status/done';
};

export type SetDoneErrors = {
    404: unknown;
    409: unknown;
    500: unknown;
};

export type SetDoneResponses = {
    200: TaskViewModel;
};

export type SetDoneResponse = SetDoneResponses[keyof SetDoneResponses];

export type SetPendingData = {
    body?: never;
    path: {
        task_id: number;
    };
    query?: never;
    url: '/tasks/{task_id}/status/pending';
};

export type SetPendingErrors = {
    404: unknown;
    409: unknown;
    500: unknown;
};

export type SetPendingResponses = {
    200: TaskViewModel;
};

export type SetPendingResponse = SetPendingResponses[keyof SetPendingResponses];
