# Shows list of recepies
default:
    just --list

# Ensure the example passes all tests and builds
test:
    just test-backend
    just build # Ensure the entire thing can build

# Builds everything
build:
    #!/usr/bin/env sh
    just generate-api-spec
    just generate-api-client
    just build-frontend
    just build-backend

    echo "\n\n-- Build artifacts --"
    ls -la backend/target/release/backend

# Cleans everything
clean:
    rm -rf backend/target
    rm -rf frontend/dist

#
# Backend
#

# Runs backend for development without static assets
[group('backend')]
[working-directory('backend')]
run-backend:
    cargo run --bin backend -- --cors-origin=http://localhost:5173,http://127.0.0.1:5173 --serve-spec

# Builds backend
[group('backend')]
[working-directory('backend')]
build-backend:
    CARGO_TARGET_DIR=./target cargo build --bin backend --release --features=static-assets

# Runs a backend helper and saves spec into spec.yaml
[group('backend')]
generate-api-spec:
    cargo run --bin spec > spec.yaml

# Runs backend tests
[group('backend')]
[working-directory('backend')]
test-backend:
    cargo test

#
# Frontend
#

# Runs frontend for development with hot-reloading and Vue devtools support
[group('frontend')]
[working-directory('frontend')]
run-frontend:
    npm run dev

# Builds frontend
[group('frontend')]
[working-directory('frontend')]
build-frontend:
    VITE_API_URL= npm run build

# Generates API client from spec
[group('frontend')]
[working-directory('frontend')]
generate-api-client: frontend-deps
    npx openapi-ts

[group('frontend')]
[working-directory('frontend')]
frontend-deps:
    #!/usr/bin/env sh
    if command -v npm > /dev/null 2>&1; then
        echo 'npm found'
    else
        echo 'Error: npm is not installed'
        exit 1
    fi

    if command -v npx > /dev/null 2>&1; then
        echo 'npx found'
    else
        echo 'Error: npx is not available'
        exit 1
    fi

    npm install

    if [ ! -f ".env" ]; then
        echo 'Warning: .env file not found; using a copy of .env.example'
        cp .env.example .env
    fi
