# Shows list of recepies
default:
    just --list

# Cleans everything
clean:
    rm -rf backend/target

#
# Backend
#

# Runs backend for development
[group('backend')]
[working-directory('backend')]
run-backend:
    cargo run --bin backend

# Builds backend
[group('backend')]
[working-directory('backend')]
build-backend:
    CARGO_TARGET_DIR=./target cargo build --bin backend --release

# Runs a backend helper and saves spec into spec.yaml
[group('backend')]
generate-api-spec:
    cargo run --bin spec > spec.yaml

# Runs backend tests
[group('backend')]
[working-directory('backend')]
test-backend:
    cargo test

#
# Frontend
#

# Generates API client from spec
[group('frontend')]
[working-directory('frontend')]
generate-api-client: frontend-deps generate-api-spec
    npx openapi-ts

[group('frontend')]
[working-directory('frontend')]
frontend-deps:
    #!/usr/bin/env sh
    if command -v npm > /dev/null 2>&1; then
        echo 'npm found'
    else
        echo 'Error: npm is not installed'
        exit 1
    fi

    if command -v npx > /dev/null 2>&1; then
        echo 'npx found'
    else
        echo 'Error: npx is not available'
        exit 1
    fi

    npm install

    if [ ! -f ".env" ]; then
        echo 'Warning: .env file not found; using a copy of .env.example'
        cp .env.example .env
    fi
