# Shows list of recepies
default:
    just --list

# Builds the example
build:
    cargo build

# Runs the example
run:
    cargo run

# Ensure the example passes all tests and builds
test:
    cargo test
    just build
